/**
 * @module @beamflow/beam-generator/python-emitter
 *
 * Low-level Python code builder with proper indentation,
 * import deduplication, and variable naming.
 *
 * This is a code string builder — it knows how to format Python
 * but knows nothing about Beam. The generator uses it to assemble
 * syntactically correct Python from IR steps.
 */

/**
 * Builds a Python source file incrementally.
 */
export class PythonEmitter {
  private readonly imports = new Set<string>();
  private readonly fromImports = new Map<string, Set<string>>();
  private readonly lines: string[] = [];
  private currentIndent = 0;
  private readonly indentStr = '    '; // 4 spaces, PEP 8

  /**
   * Add a top-level import (e.g., 'import json').
   */
  addImport(module: string): void {
    this.imports.add(module);
  }

  /**
   * Add a from...import statement (e.g., from apache_beam import Pipeline).
   * Multiple imports from the same module are grouped.
   */
  addFromImport(module: string, name: string): void {
    if (!this.fromImports.has(module)) {
      this.fromImports.set(module, new Set());
    }
    this.fromImports.get(module)!.add(name);
  }

  /**
   * Add a blank line.
   */
  blank(): void {
    this.lines.push('');
  }

  /**
   * Add a line of code at the current indentation level.
   */
  line(code: string): void {
    const indent = this.indentStr.repeat(this.currentIndent);
    this.lines.push(`${indent}${code}`);
  }

  /**
   * Add a comment line.
   */
  comment(text: string): void {
    this.line(`# ${text}`);
  }

  /**
   * Increase indentation for subsequent lines.
   */
  indent(): void {
    this.currentIndent++;
  }

  /**
   * Decrease indentation.
   */
  dedent(): void {
    if (this.currentIndent > 0) this.currentIndent--;
  }

  /**
   * Add a block (e.g., 'with beam.Pipeline() as p:') and auto-indent.
   * Call dedent() when done with the block.
   */
  block(header: string): void {
    this.line(header);
    this.indent();
  }

  /**
   * Build the final Python source code string.
   * Imports are deduplicated and placed at the top.
   */
  build(): string {
    const parts: string[] = [];

    // File header
    parts.push('"""');
    parts.push('Auto-generated by BeamFlow');
    parts.push('Do not edit manually — regenerate from the workflow editor.');
    parts.push('"""');
    parts.push('');

    // Standard imports
    const sortedImports = Array.from(this.imports).sort();
    for (const imp of sortedImports) {
      parts.push(`import ${imp}`);
    }
    if (sortedImports.length > 0) parts.push('');

    // From imports (grouped by module, sorted)
    const sortedFromModules = Array.from(this.fromImports.keys()).sort();
    for (const module of sortedFromModules) {
      const names = Array.from(this.fromImports.get(module)!).sort();
      if (names.length <= 3) {
        parts.push(`from ${module} import ${names.join(', ')}`);
      } else {
        parts.push(`from ${module} import (`);
        for (const name of names) {
          parts.push(`    ${name},`);
        }
        parts.push(')');
      }
    }
    if (sortedFromModules.length > 0) parts.push('');

    // Body
    parts.push('');
    parts.push(...this.lines);

    // Ensure trailing newline
    const result = parts.join('\n');
    return result.endsWith('\n') ? result : result + '\n';
  }
}

/**
 * Convert a node/step ID to a valid Python variable name.
 * Replaces non-alphanumeric characters with underscores.
 */
export function toPythonVar(id: string): string {
  return id.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^([0-9])/, '_$1');
}

/**
 * Short distinct suffix derived from a step/node id, e.g. `node_a1b2c3d4` → `a1b2c3d4`,
 * `abc__s2` → `abc_s2`. Sanitized to id-safe chars. This is what makes two same-named
 * nodes produce distinct code names.
 */
function idSuffix(id: string): string {
  // Prefer the part after the last `_` (our ids are `node_<nanoid>`); fall back to
  // the whole id. Always sanitize.
  const raw = id.includes('_') ? id.slice(id.lastIndexOf('_') + 1) : id;
  const safe = raw.replace(/[^a-zA-Z0-9]/g, '');
  return safe || id.replace(/[^a-zA-Z0-9]/g, '') || 'x';
}

/**
 * The shared naming base for a node's generated code: `<labelPrefix>_<idSuffix>`.
 *
 * Both the pcollection variable name AND the Beam transform label derive from this so
 * they share a prefix (the human node label) and carry the same distinct id suffix —
 * satisfying "variable name and label name prefix should be the same" while guaranteeing
 * uniqueness (the id is unique per node, so two "Filter" nodes never collide — which also
 * prevents Beam's runtime "duplicate transform label" error).
 *
 * `label` is the (possibly user-edited) node label; `id` is the unique step/node id.
 */
export function nodeNameBase(label: string, id: string): string {
  const prefix = (label || '').replace(/[^a-zA-Z0-9]+/g, '_').replace(/^_+|_+$/g, '');
  const base = prefix || 'step';
  return `${base}_${idSuffix(id)}`;
}

/** The pcollection variable name for a node: lower-snake, from the shared base. */
export function pcollVarName(label: string, id: string): string {
  return toPythonVar(nodeNameBase(label, id).toLowerCase());
}

/** The Beam transform label string for a node: the shared base, verbatim (id-safe). */
export function stepLabelName(label: string, id: string): string {
  return nodeNameBase(label, id);
}

/**
 * Escape a string for use in a Python string literal.
 */
export function toPythonString(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
}
