/**
 * @module @beamflow/beam-generator/python-emitter
 *
 * Low-level Python code builder with proper indentation,
 * import deduplication, and variable naming.
 *
 * This is a code string builder — it knows how to format Python
 * but knows nothing about Beam. The generator uses it to assemble
 * syntactically correct Python from IR steps.
 */

/**
 * Builds a Python source file incrementally.
 */
export class PythonEmitter {
  private readonly imports = new Set<string>();
  private readonly fromImports = new Map<string, Set<string>>();
  private readonly lines: string[] = [];
  private currentIndent = 0;
  private readonly indentStr = '    '; // 4 spaces, PEP 8

  /**
   * Add a top-level import (e.g., 'import json').
   */
  addImport(module: string): void {
    this.imports.add(module);
  }

  /**
   * Add a from...import statement (e.g., from apache_beam import Pipeline).
   * Multiple imports from the same module are grouped.
   */
  addFromImport(module: string, name: string): void {
    if (!this.fromImports.has(module)) {
      this.fromImports.set(module, new Set());
    }
    this.fromImports.get(module)!.add(name);
  }

  /**
   * Add a blank line.
   */
  blank(): void {
    this.lines.push('');
  }

  /**
   * Add a line of code at the current indentation level.
   */
  line(code: string): void {
    const indent = this.indentStr.repeat(this.currentIndent);
    this.lines.push(`${indent}${code}`);
  }

  /**
   * Add a comment line.
   */
  comment(text: string): void {
    this.line(`# ${text}`);
  }

  /**
   * Increase indentation for subsequent lines.
   */
  indent(): void {
    this.currentIndent++;
  }

  /**
   * Decrease indentation.
   */
  dedent(): void {
    if (this.currentIndent > 0) this.currentIndent--;
  }

  /**
   * Add a block (e.g., 'with beam.Pipeline() as p:') and auto-indent.
   * Call dedent() when done with the block.
   */
  block(header: string): void {
    this.line(header);
    this.indent();
  }

  /**
   * Build the final Python source code string.
   * Imports are deduplicated and placed at the top.
   */
  build(): string {
    const parts: string[] = [];

    // File header
    parts.push('"""');
    parts.push('Auto-generated by BeamFlow');
    parts.push('Do not edit manually — regenerate from the workflow editor.');
    parts.push('"""');
    parts.push('');

    // Standard imports
    const sortedImports = Array.from(this.imports).sort();
    for (const imp of sortedImports) {
      parts.push(`import ${imp}`);
    }
    if (sortedImports.length > 0) parts.push('');

    // From imports (grouped by module, sorted)
    const sortedFromModules = Array.from(this.fromImports.keys()).sort();
    for (const module of sortedFromModules) {
      const names = Array.from(this.fromImports.get(module)!).sort();
      if (names.length <= 3) {
        parts.push(`from ${module} import ${names.join(', ')}`);
      } else {
        parts.push(`from ${module} import (`);
        for (const name of names) {
          parts.push(`    ${name},`);
        }
        parts.push(')');
      }
    }
    if (sortedFromModules.length > 0) parts.push('');

    // Body
    parts.push('');
    parts.push(...this.lines);

    // Ensure trailing newline
    const result = parts.join('\n');
    return result.endsWith('\n') ? result : result + '\n';
  }
}

/**
 * Convert a node/step ID to a valid Python variable name.
 * Replaces non-alphanumeric characters with underscores.
 */
export function toPythonVar(id: string): string {
  return id.replace(/[^a-zA-Z0-9_]/g, '_').replace(/^([0-9])/, '_$1');
}

/**
 * Escape a string for use in a Python string literal.
 */
export function toPythonString(value: string): string {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r');
}
